#TODO DOCKERFILE INICIA POR FROM QUE DEVE SER APONTADO A IMG DE ORIGEM, RECOMENDA-SE QUE ESSA IMG SEJA PEQUENA
FROM alpine:3.19
#COMANDO PARA INSTALAR COISAS NA IMG
RUN apk add openjdk21-jre
#SETA UM COMANDO QUE SERA EXECUTADO APENAS QUANDO UM CONTAINER FOR CRIADO A PARTIR DA IMG, ENQUANTO O RUN EH EXECUTADO EM BUILD
CMD java -version